apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: websearch-api

resources:
  - namespace.yaml
  - configmap.yaml
  - keycloak-secret.yaml
  - mongodb.yaml
  - redis.yaml
  - api-deployment.yaml
  - dashboard-deployment.yaml
  - prometheus.yaml
  - grafana.yaml
  - jaeger.yaml
  - otel-collector.yaml
  - ingress.yaml

images:
  - name: websearch-api
    newTag: "0.1.7"
  - name: websearch-dashboard
    newTag: "0.1.7"
